[package]
name = "stafi-primitives"
version = "0.1.0"
authors = ["Stafi Protocol"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
client = { package = "substrate-client", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
parity-codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
primitives = { package = "substrate-primitives", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }

[dev-dependencies]
substrate-serializer = { git = "https://github.com/stafiprotocol/stafi-blockchain" }
pretty_assertions = "0.5"

[features]
default = ["std"]
std = [
	"client/std",
	"parity-codec/std",
	"primitives/std",
	"rstd/std",
	"runtime_primitives/std",
	"serde",
]
