[package]
name = "stafi-runtime"
version = "0.1.0"
authors = ["Stafi Protocol"]
edition = "2018"
build = "build.rs"

[dependencies]
integer-sqrt = { version = "0.1.2" }
safe-mix = { version = "1.0", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
substrate-primitives = { git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
client = { package = "substrate-client", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
sr-staking-primitives = { package = "sr-staking-primitives", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
offchain-primitives = { package = "substrate-offchain-primitives", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
version = { package = "sr-version", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
support = { package = "srml-support", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
authorship = { package = "srml-authorship", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
babe = { package = "srml-babe", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
babe-primitives = { package = "substrate-consensus-babe-primitives", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
balances = { package = "srml-balances", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
contracts = { package = "srml-contracts", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
collective = { package = "srml-collective", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
democracy = { package = "srml-democracy", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
elections = { package = "srml-elections", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
executive = { package = "srml-executive", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
finality-tracker = { package = "srml-finality-tracker", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
grandpa = { package = "srml-grandpa", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
indices = { package = "srml-indices", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
membership = { package = "srml-membership", git ="https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
session = { package = "srml-session", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false, features = ["historical"] }
staking = { package = "srml-staking", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
system = { package = "srml-system", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
timestamp = { package = "srml-timestamp", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
treasury = { package = "srml-treasury", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
sudo = { package = "srml-sudo", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
im-online = { package = "srml-im-online", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
offences = { package = "srml-offences", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
rustc-hex = { version = "2.0", optional = true }
serde = { version = "1.0", optional = true }
substrate-keyring = { git = "https://github.com/stafiprotocol/stafi-blockchain", optional = true }
substrate-session = { git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
authority-discovery-primitives = { package = "substrate-authority-discovery-primitives", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }
authority-discovery = { package = "srml-authority-discovery", git = "https://github.com/stafiprotocol/stafi-blockchain", default-features = false }

stafi-staking = { path = "../modules/stafi-staking", default-features = false }
tokenbalances = { path = "../modules/tokenbalances", default-features = false }
stafi-multisig = { path = "../modules/stafi-multisig", default-features = false }

stafi-primitives = { path = "../primitives", default-features = false }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.2", git = "https://github.com/stafiprotocol/stafi-blockchain" }

[features]
default = ["std"]
no_std = [
	"contracts/core",
]
std = [
	"authority-discovery-primitives/std",
	"authority-discovery/std",
	"codec/std",
	"substrate-primitives/std",
	"rstd/std",
	"runtime_primitives/std",
	"support/std",
	"authorship/std",
	"babe/std",
	"babe-primitives/std",
	"balances/std",
	"contracts/std",
	"collective/std",
	"democracy/std",
	"elections/std",
	"executive/std",
	"finality-tracker/std",
	"grandpa/std",
	"indices/std",
	"membership/std",
	"session/std",
	"staking/std",
	"system/std",
	"timestamp/std",
	"treasury/std",
	"sudo/std",
	"version/std",
	"serde",
	"safe-mix/std",
	"client/std",
	"rustc-hex",
	"substrate-keyring",
	"offchain-primitives/std",
	"im-online/std",
	"offences/std",
	"substrate-session/std",
	"stafi-staking/std",
	"tokenbalances/std",
	"stafi-multisig/std",
	"stafi-primitives/std",
]
